### ISSUE TITLE
Support for creating tests at runtime

### ISSUE THREAD

**Issue by bartekpacia** [swiftlang/swift-testing#696]
Hey!

I've not used this library yet, but it looks great. I'm curious if it supports creating tests at runtime. It's a rare case for app developers, but as a tooling developer, I badly needed this once and [`XCTestCase.testInvocations`](https://developer.apple.com/documentation/xctest/xctestcase/1496271-testinvocations) saved me – though it's only accessibly from Objective-C.

Here's an example, simple usage of [`testInvocations`](https://stackoverflow.com/questions/77494930/does-xctest-methods-generated-dynamically-by-testinvocations-work-with-xcodebuil).

My question is: what's this library's stance on dynamic creation of tests at runtime? Is it already supported? I think a mention in the README would do:)

Cheers!

**Comment by stmontgomery** [comment]
In Swift Testing this technique is referred to as Parameterized Testing and it's well supported and encouraged! For some details see https://swiftpackageindex.com/swiftlang/swift-testing/0.12.0/documentation/testing

Since this is just a general inquiry and not a specific bug report or enhancement request I'm going to close this issue. I'd encourage you to post on the Forums in the [swift-testing](https://forums.swift.org/c/related-projects/swift-testing/103) category with any follow up questions.
